#!/bin/sh
exec tail -n +3 $0
menuentry 'Read Only System' --class debian --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-9f7317f1-a037-4b4b-9ab7-6ebd5f28e5f9' {
	load_video
	insmod gzio
	if [ x$grub_platform = xxen ]; then insmod xzio; insmod lzopio; fi
	insmod part_msdos
	insmod ext2
	set root='hd0,msdos1'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos1  9f7317f1-a037-4b4b-9ab7-6ebd5f28e5f9
	else
	  search --no-floppy --fs-uuid --set=root 9f7317f1-a037-4b4b-9ab7-6ebd5f28e5f9
	fi
	echo	'Wczytywanie systemu Linux 4.19.0-9-amd64...'
	linux	/boot/vmlinuz-4.19.0-9-amd64 root=UUID=9f7317f1-a037-4b4b-9ab7-6ebd5f28e5f9 ro  quiet aufs=tmpfs
	echo	'Wczytywanie początkowego dysku RAM...'
	initrd	/boot/initrd.img-4.19.0-9-amd64
}
menuentry 'SERVICE MODE' --class debian --class gnu-linux --class gnu --class os $menuentry_id_option 'gnulinux-simple-9f7317f1-a037-4b4b-9ab7-6ebd5f28e5f9' {
	load_video
	insmod gzio
	if [ x$grub_platform = xxen ]; then insmod xzio; insmod lzopio; fi
	insmod part_msdos
	insmod ext2
	set root='hd0,msdos1'
	if [ x$feature_platform_search_hint = xy ]; then
	  search --no-floppy --fs-uuid --set=root --hint-bios=hd0,msdos1 --hint-efi=hd0,msdos1 --hint-baremetal=ahci0,msdos1  9f7317f1-a037-4b4b-9ab7-6ebd5f28e5f9
	else
	  search --no-floppy --fs-uuid --set=root 9f7317f1-a037-4b4b-9ab7-6ebd5f28e5f9
	fi
	echo	'Wczytywanie systemu Linux 4.19.0-9-amd64...'
	linux	/boot/vmlinuz-4.19.0-9-amd64 root=UUID=9f7317f1-a037-4b4b-9ab7-6ebd5f28e5f9 ro  quiet 
	echo	'Wczytywanie początkowego dysku RAM...'
	initrd	/boot/initrd.img-4.19.0-9-amd64
}
